"""Add User model and Video foreign key

Revision ID: 2f4dc70b791b
Revises: f199003e72af
Create Date: 2026-06-18 20:36:44.129252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f4dc70b791b'
down_revision: Union[str, Sequence[str], None] = 'f199003e72af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_videos_owner_id_users'), 'users', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_videos_owner_id_users'), type_='foreignkey')

    # ### end Alembic commands ###
