"""Add Users table and video owner relationship

Revision ID: 95cfbac09841
Revises: 2f4dc70b791b
Create Date: 2026-06-18 20:37:45.176465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95cfbac09841'
down_revision: Union[str, Sequence[str], None] = '2f4dc70b791b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
